export const Category1 = [
    {
        id:1,
        name:'arts',
        label:'Arts'
    },
    {
        id:2,
        name:'automobiles',
        label:'Automobiles'
    },
    {
        id:3,
        name:'books',
        label:'Books'
    },
    {
        id:4,
        name:'business',
        label:'Business'
    },
    {
        id:5,
        name:'fashion',
        label:'Fashion'
    },
    {
        id:6,
        name:'food',
        label:'Food'
    },
    {
        id:7,
        name:'health',
        label:'Health'
    },
    {
        id:8,
        name:'home',
        label:'Home'
    },
    {
        id:9,
        name:'insider',
        label:'Insider'
    },
    {
        id:10,
        name:'magazine',
        label:'Magazine'
    },
    {
        id:11,
        name:'movies',
        label:'Movies'
    },
    {
        id:12,
        name:'nyregion',
        label:'Nyregion'
    },
    {
        id:13,
        name:'obituaries',
        label:'Obituaries'
    },
    
]
export const Category2 = [
    {
        id:14,
        name:'opinion',
        label:'Opinion'
    },
    {
        id:15,
        name:'politics',
        label:'Politics'
    },
    {
        id:16,
        name:'realestate',
        label:'Realestate'
    },
    {
        id:17,
        name:'science',
        label:'Science'
    },
    {
        id:18,
        name:'sports',
        label:'Sports'
    },
    {
        id:19,
        name:'sundayreview',
        label:'SundayReview'
    },
    {
        id:20,
        name:'technology',
        label:'Tech'
    },
    {
        id:21,
        name:'theater',
        label:'Theater'
    },
    {
        id:22,
        name:' t-magazine',
        label:'T-Magazine'
    },
    {
        id:23,
        name:'travel',
        label:'Travel'
    },
    {
        id:24,
        name:'upshot',
        label:'Upshot'
    },
    {
        id:25,
        name:'us',
        label:'US'
    },
    {
        id:26,
        name:'world',
        label:'World'
    },
    
]